"""empty message

Revision ID: 2f69a6a058e1
Revises: fd1d12fd2a5d
Create Date: 2023-09-13 19:19:46.904479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f69a6a058e1'
down_revision = 'fd1d12fd2a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('gravity', sa.String(length=250), nullable=True))
        batch_op.drop_column('population')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('gravity')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
